### ISSUE TITLE
Add 3D translations and scale

### ISSUE THREAD

**Issue by jnk22** [tlambert03/napari-manual-transforms#1]
Hi, are you interested in adding translation and scale for 3D layers?

I have implemented both in my fork: https://github.com/jnk22/napari-manual-transforms/tree/feat_translation-scale-3d

If so, I would be happy to open a pull request and provide some more context if needed.

**Comment by tlambert03** [comment]
hey @jnk22, I'm not personally doing too much with napari these days, but would be more than happy to review and merge your PR if you'd like it to be part of the plugin.  I took  quick look at your branch and it seems well designed.

**Comment by jnk22** [comment]
Thanks for your quick reply!

I have now opened #2.
